name: Test
on:
    push:
        branches:
            - main
            - dev
    pull_request:
        branches:
            - main
            - dev
            
jobs:
    Check-Updates:
        runs-on: ubuntu-latest
        outputs:
            upstream_tag: ${{ steps.check.outputs.upstream_tag }}
        steps:
            - name: Checkout repo
              uses: actions/checkout@v6

            - name: Check upstream
              id: check
              run: |
                  # get newest tag from official equicord repo
                  UPSTREAM=$(gh api repos/Equicord/Equicord/releases/latest --jq .tag_name)
                  echo "upstream_tag=$UPSTREAM" >> "$GITHUB_OUTPUT"
                  
                  # check if we already pushed this tag to our fork
                  if git ls-remote --tags origin | grep -q "refs/tags/$UPSTREAM"; then
                      echo "already up to date with $UPSTREAM! aborting workflow."
                      exit 1 # this forcefully crashes and fails the job!
                  else
                      echo "new version found: $UPSTREAM!"
                  fi
                  
    Test:
        name: Test
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v6
            - uses: pnpm/action-setup@v6 # Install pnpm using packageManager key in package.json

            - name: Use Node.js 24
              uses: actions/setup-node@v6
              with:
                  node-version: 24
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Lint & Test if desktop version compiles
              run: pnpm test

            - name: Test if web version compiles
              run: pnpm buildWeb

            - name: Test if plugin structure is valid
              run: pnpm generatePluginJson
